/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.design.Conversor;

/**
 *
 * @author Wolf390
 */
public class ConversorGui extends javax.swing.JFrame {

    /**
     * Creates new form ConversorGui
     */
    public ConversorGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgOpcoes = new javax.swing.ButtonGroup();
        pnlTemperratura = new javax.swing.JPanel();
        lblTemperatura = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        txtTemperatura = new javax.swing.JTextField();
        pnlOpcoes = new javax.swing.JPanel();
        rbtCelFah = new javax.swing.JRadioButton();
        rbtFahCel = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTemperratura.setBackground(new java.awt.Color(153, 0, 51));

        lblTemperatura.setForeground(new java.awt.Color(255, 255, 255));
        lblTemperatura.setText("Conversor de °C: ");

        lblResultado.setBackground(new java.awt.Color(204, 0, 51));
        lblResultado.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(255, 255, 255));

        btnCalcular.setText("Calcular ");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        txtTemperatura.setForeground(new java.awt.Color(255, 255, 255));
        txtTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperaturaActionPerformed(evt);
            }
        });

        pnlOpcoes.setBackground(new java.awt.Color(153, 0, 102));
        pnlOpcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções "));
        pnlOpcoes.setForeground(new java.awt.Color(255, 255, 255));

        rbtCelFah.setBackground(new java.awt.Color(153, 0, 51));
        btgOpcoes.add(rbtCelFah);
        rbtCelFah.setSelected(true);
        rbtCelFah.setText("C para F");
        rbtCelFah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCelFahActionPerformed(evt);
            }
        });

        rbtFahCel.setBackground(new java.awt.Color(153, 0, 51));
        btgOpcoes.add(rbtFahCel);
        rbtFahCel.setText("F para C");
        rbtFahCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtFahCelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOpcoesLayout = new javax.swing.GroupLayout(pnlOpcoes);
        pnlOpcoes.setLayout(pnlOpcoesLayout);
        pnlOpcoesLayout.setHorizontalGroup(
            pnlOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcoesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtCelFah)
                    .addComponent(rbtFahCel))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        pnlOpcoesLayout.setVerticalGroup(
            pnlOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcoesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rbtCelFah)
                .addGap(36, 36, 36)
                .addComponent(rbtFahCel)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTemperraturaLayout = new javax.swing.GroupLayout(pnlTemperratura);
        pnlTemperratura.setLayout(pnlTemperraturaLayout);
        pnlTemperraturaLayout.setHorizontalGroup(
            pnlTemperraturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTemperraturaLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(pnlTemperraturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTemperraturaLayout.createSequentialGroup()
                        .addGroup(pnlTemperraturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTemperraturaLayout.createSequentialGroup()
                                .addComponent(lblTemperatura)
                                .addGap(18, 18, 18)
                                .addComponent(txtTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTemperraturaLayout.createSequentialGroup()
                                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)))
                        .addComponent(pnlOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTemperraturaLayout.createSequentialGroup()
                        .addComponent(btnCalcular)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar)
                        .addGap(131, 131, 131))))
        );
        pnlTemperraturaLayout.setVerticalGroup(
            pnlTemperraturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTemperraturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTemperraturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTemperraturaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(pnlOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlTemperraturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpar)
                            .addComponent(btnCalcular))
                        .addContainerGap())
                    .addGroup(pnlTemperraturaLayout.createSequentialGroup()
                        .addGroup(pnlTemperraturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTemperatura))
                        .addGap(49, 49, 49)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTemperratura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTemperratura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        
        //Declaração de Variáveis.
        double cel, fah;
        
        //Criação e Instância Objeto da Classe Conversor.
        Conversor conversor = new Conversor();
        
        if(rbtCelFah.isSelected()){
            try{  
                //Entrada
                cel = Double.parseDouble(txtTemperatura.getText());
        
                //Sáida.
                lblResultado.setText(conversor.celFah(cel) + "°C");
                
            }catch(NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage(), "Ops!", 0);
            }            
        }else{
            try{  
                //Entrada
                fah = Double.parseDouble(txtTemperatura.getText());
        
                //Sáida.
                lblResultado.setText(conversor.fahCel(fah) + "°F");
                
            }catch(NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage(), "Ops!", 0);
            }             
        }

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        
        //Limpando o Campo.
        txtTemperatura.setText(null);
        lblResultado.setText(null);
        
        //Colocando o Cursor no Text View.
        txtTemperatura.requestFocus();
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void rbtCelFahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCelFahActionPerformed
        // TODO add your handling code here:
        lblTemperatura.setText("Temperatura  °C: ");
        btnLimparActionPerformed(evt);
    }//GEN-LAST:event_rbtCelFahActionPerformed

    private void txtTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperaturaActionPerformed

    private void rbtFahCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtFahCelActionPerformed
        // TODO add your handling code here:
        lblTemperatura.setText("Temperatura °F: ");
        btnLimparActionPerformed(evt);
    }//GEN-LAST:event_rbtFahCelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgOpcoes;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTemperatura;
    private javax.swing.JPanel pnlOpcoes;
    private javax.swing.JPanel pnlTemperratura;
    private javax.swing.JRadioButton rbtCelFah;
    private javax.swing.JRadioButton rbtFahCel;
    private javax.swing.JTextField txtTemperatura;
    // End of variables declaration//GEN-END:variables
}
